[96mconfig: {
[96m    "batch_size": 1024,
[96m    "buffer_size": 10240,
[96m    "clip_range": 0.2,
[96m    "debug_env": false,
[96m    "env_id": "MyUnityGymEnv-v0",
[96m    "env_path": "drone3D_linux_run61.3c/mse-dreamscape",
[96m    "export_onnx": false,
[96m    "gae_lambda": 0.95,
[96m    "gamma": 0.99,
[96m    "has_continuous_action_space": true,
[96m    "log_TFSideStats": false,
[96m    "lr_actor": 0.0003,
[96m    "lr_critic": 0.001,
[96m    "n_epochs": 3,
[96m    "no_graphics": true,
[96m    "num_env": 1,
[96m    "reinitialize_from": "run-20211004_161556-cdp0bn8h",
[96m    "run_dir": "/app/wandb/run-20211017_175924-1259pi7b/files",
[96m    "test_total_episodes": 0,
[96m    "time_scale": 50,
[96m    "total_timesteps": 200,
[96m    "worker_id": 1
[96m}
Device set to : cpu
[96mMonitor base path: /app/wandb/run-20211017_175924-1259pi7b/files/monitor
[91mReinitializing training from run: /app/wandb/run-20211017_175924-1259pi7b/files/model
------------------------------------------------------------------------------
Total execution time: 0.00 seconds
[96mInitializing env with rank: 0
[91mInitializing SB3StatsRecorder
Process ForkServerProcess-2:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ros/.local/lib/python3.7/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 24, in _worker
    env = env_fn_wrapper.var()
  File "/app/trainer.py", line 210, in _init
    env = environment_controller.make_env()
  File "/app/environment_controller.py", line 84, in make_env
    env = gym.make(config.env_id)
  File "/home/ros/.local/lib/python3.7/site-packages/gym/envs/registration.py", line 235, in make
    return registry.make(id, **kwargs)
  File "/home/ros/.local/lib/python3.7/site-packages/gym/envs/registration.py", line 129, in make
    env = spec.make(**kwargs)
  File "/home/ros/.local/lib/python3.7/site-packages/gym/envs/registration.py", line 90, in make
    env = cls(**_kwargs)
  File "/app/environment_controller.py", line 197, in __init__
    env = get_wandb_ue_env()
  File "/app/environment_controller.py", line 96, in get_wandb_ue_env
    channel = SB3StatsRecorder()
  File "/app/environment_controller.py", line 135, in __init__
    self.connection = pika.BlockingConnection(params)
  File "/home/ros/.local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "/home/ros/.local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
  File "/home/ros/.local/lib/python3.7/site-packages/pika/adapters/utils/selector_ioloop_adapter.py", line 567, in _resolve
    self._flags)
  File "/opt/conda/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    main()
  File "main.py", line 9, in main
    m_Trainer.model_pipeline()
  File "/app/trainer.py", line 44, in _time_it
    return func(*args, **kwargs)
  File "/app/trainer.py", line 163, in model_pipeline
    env = SubprocVecEnv([self._make_my_vec_env(self.config.env_id, i, self.callback) for i in range(idx_r, num_cpu + idx_r)])
  File "/home/ros/.local/lib/python3.7/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 111, in __init__
    observation_space, action_space = self.remotes[0].recv()
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
------------------------------------------------------------------------------
Total execution time: 21.77 seconds